teacherfund/TeacherFund_next

- components/loginform.js
- components/subsectionBasic.js
- package-lock.json
- pages/signInSignUp.js
- static/styles/main.scss
- static/styles/partials/footer.scss
- static/styles/partials/login.scss
- static/styles/reset.scss
- static/styles/variables.scss
> Basic structure of login form component

- pages/aboutus.js
- pages/donate.js
- pages/index.js
- pages/ourwork.js
- pages/signInSignUp.js
- pages/whyteachers.js
- static/styles/main.scss
- static/styles/partials/footer.scss
- static/styles/partials/home.scss
> Keep footer at bottom of page

- components/donateform.js
- components/emailCapture.js
- components/footer.js
- components/nav.js
- components/subsectionBasic.js
- components/swiper.js
- components/twoItemSwitcher.js
- pages/aboutus.js
- static/styles/main.scss
> Use text transform for uppercase content

- components/employeeInfo.js
- components/subsectionBasic.js
- pages/aboutus.js
- static/styles/partials/_aboutus.scss
Relating to https://github.com/teacherfund/TeacherFund_next/issues/23
> Add responsiveness to About page

- pages/aboutus.js
- static/styles/partials/_aboutus.scss
Fixed About page background to original white
Removed unused CSS. This CSS is no longer used because the SubsectionBasic component was added to this page
Fix EmployeeInfo component key error
Relating to https://github.com/teacherfund/TeacherFund_next/issues/23
Mobile:
Desktop:
> Correct About page background

- static/styles/main.scss
- static/styles/partials/_navigation.scss
- static/styles/variables.scss
https://github.com/teacherfund/TeacherFund_next/issues/13
Header: Oswald medium, 20 pt font, 24 pt leading
> Add global font specifics for nav elements.

- components/emailCapture.js
- static/styles/partials/_emailcapture.scss
- static/styles/variables.scss
https://github.com/teacherfund/TeacherFund_next/issues/18
Refactor emailCapture component to follow BEM style.
> Refactor SCSS structure

- components/loginform.js
- components/nav.js
- pages/signinregister.js
Hi there,
I have completed the enhancement, if you click the `I'm a teacher` button on the Home page, it will take you to the sign in page with `I'm a teacher` selected.
I had to change the initial state for `loginType` to get the things working correctly. 
Please have a look and let me know if there is any issue in it.
Thank you!
> Toggle button enhancement for [issue #55] done!

- containers/withContext.js
- pages/_app.js
Added some comments to explain how it works in practice.
> Add context container

- pages/index.js
Added a regex validation to the subscribe method in index.js. If the input value of the email field doesn't match the expression, it returns an error message of "Please enter a valid Email".
> regex validation for subscribe method Issue #89

- pages/index.js
Issue 89 was closed with my previous pull request updating the regex for email validation. 
I've now split the input field into first and last name as was discussed in that issue.
> split name field in subscribe form into first and last name - issue #89 

- pages/index.js
Small PR - The title and sub title in the hero image does have sufficient color contrast that meets WCAG 2 AA contrast ration thresholds. Changed the color to be white for better contrast.
> Heading color contrast update to meet accessibility standards.

- pages/success.js
I added the button per the issue and styled it like buttons on the index.js page. 
Please let me know if you'd like me to add any hashtags to the tweet. Some ideas would be #donate, #teacherfund, #makeadifference.
> add tweet this button issue #96

- .babelrc
- api/api.js
- components/donateform.js
- containers/withContext.js
- package-lock.json
- package.json
- pages/success.js
- test/_register.js
- test/containers/withContext.test.js
This covers main need of #28. After other screen sizes are implemented according to the design, we should add Enzyme tests to keep the UI from regressing.
> Add testing framework and withContext tests

- components/loginform.js
- pages/account.js
- pages/index.js
Added aria labels to clarify sections and updated alt tags
> Accessibility tags

- pages/_document.js
This is a fix for one of the big accessibility issues with the site.
> Add 'lang' attribute to html

- pages/mission.js
New text added on mission page as per #147 
Donate button  added and styled like button on pages/index.js
> mission page text updated & button added

- components/donateform.js
- components/nav.js
- components/pageWrapper.js
- pages/account.js
- pages/donate.js
- pages/error.js
- pages/index.js
- pages/mission.js
- pages/pending-login.js
- pages/signin.js
- pages/success.js
- static/styles/partials/_components.scss
- static/styles/partials/_display.scss
> Add PageWrapper component and skip link

- components/heroImage.js
- pages/index.js
- static/styles/partials/_fonts.scss
- static/styles/partials/_indexpage.scss
- static/styles/partials/_spacing.scss
I didn't do anything with the font sizes/ spacing yet but the spacing between the bar and the pencil tips is fixed across all device widths.
> Responsive hero (Issue 162)

- components/donateform.js
- package-lock.json
- package.json
- pages/donate.js
This PR addresses issue #165. I followed @joelwass's requirements and also React Stripe.js's [migrating docs](https://github.com/stripe/react-stripe-js/blob/master/docs/migrating.md).
> Migrate from react-stripe-elements to React Stripe.js (#165)
